In [2]:
# Convolution using filter2D: Negative values allowed
import cv2 as cv
import numpy as np

In [3]:
# Input matrix (image-like)
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=np.uint8)

# Sobel kernel for horizontal edge detection
b = np.array([[-1, 0, 1],
              [-2, 0, 2],
              [-1, 0, 1]], dtype=np.float32)

print("Input Matrix (a):")
print(a)

print("\nSobel Kernel (b):")
print(b)

# Flip the kernel for true convolution
b1 = cv.flip(b, -1)

# Apply convolution
c = cv.filter2D(src=a, ddepth=cv.CV_32F, kernel=b1, borderType=cv.BORDER_CONSTANT)

print("\nOutput Matrix after Convolution:")
print(c)


Input Matrix (a):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sobel Kernel (b):
[[-1.  0.  1.]
 [-2.  0.  2.]
 [-1.  0.  1.]]

Output Matrix after Convolution:
[[ -9.  -6.   9.]
 [-20.  -8.  20.]
 [-21.  -6.  21.]]
